pipeline:

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t dq-postgres-docker .
    when:
      branch: master
      event: push


  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_username
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
      - docker tag dq-postgres-docker quay.io/ukhomeofficedigital/dq-postgres-docker:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/dq-postgres-docker:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push
