pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-postgres-docker
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    force_tag: true
    tags:
      - latest
    when:
      event: push
